various fixes -see the source code

diff --git a/scripts/print_security_patch b/scripts/print_security_patch
--- a/scripts/print_security_patch
+++ b/scripts/print_security_patch
@@ -17,6 +17,12 @@
 #     The config file used to define the patchlevel and the release changed again in Android 15:
 #     The script now reads the config from the file ./build/core/build_id.mk if it exists
 #
+#  16.01.2025 v1.3.0.0 /bs
+#     the script now supports parameter to set variables; the format for the parameter is: "var=value"
+#     added code to print the build command for creating the ROM image file (use the parameter PRINT=0 to print the command)
+#     added code to print the global variables found in the repository tree (use the parameter PRINTVARS=0 to print the variables and values)
+#     added support for the environment variables ROM_TYPE and TARGET_PHONE
+#
 
 #h# 
 #h# This script works for repositories that were last updated before and after the release of Android 14 QPR2 (in Q1 2024)
@@ -28,8 +34,20 @@
 #
 #h# Usage: 
 #h# 
-#h#    print_security_patch [rom_zip_file|repository_tree] [...]
+#h#    print_security_patch [rom_zip_file|repository_tree] [var=value] [...]
 #h# 
+#h# Known values for the parameter "var=value":
+#h# 
+#h# Parameter                  Description
+#h# ---------------------------------------------------------------------------------------
+#h# PRINT=0                    Print the command to build the image for repositories
+#h# PRINTVARS=0                Print the value for the global variables set by this script
+#h# 
+#h# VERBOSE=0                  Turn on verbose messages
+#h# ROM_TYPE=<romtype>         Change the type of the ROM used in the build command (user, eng, or debug)
+#h# TARGET_PHONE=<phone_name>  Change the type of the phone used in the build command
+#h# 
+
 # Without the parameter the script prints the security patch level of the repository tree starting at the current working directory
 #
 # If used like this
@@ -41,6 +59,11 @@
 #    RELEASE_PLATFORM_SECURITY_PATCH
 #    BUILD_ID
 #    REPO_FORMAT
+#
+# and  if the parameter PRINT=0 is used
+#
+#    BUILD_COMMAND
+#
 #
 # Returncodes:
 # 
@@ -54,6 +77,7 @@
 #  203 - The statement post-security-patch-level= is missing in the file META-INF/com/android/metadata
 #  240 - Can not change the working directory to the directory found in the parameter
 #  250 - Invalid parameter
+#  251 - Invalid parameter to set a variable
 #
 
 # ---------------------------------------------------------------------
@@ -62,10 +86,23 @@
 [ "${DEBUG}"x != ""x ] && set -x
 
 # ---------------------------------------------------------------------
+# define constants
+
+typeset -r __TRUE=0
+typeset -r __FALSE=1
+
+# ---------------------------------------------------------------------
 # get the script name and version
 #
 SCRIPT_VERSION="$( grep "#.*/bs" $0 | grep -v grep | tail -1 | awk '{ print $3}' )"
 SCRIPT_NAME="${0##*/}"
+
+# ---------------------------------------------------------------------
+# variables for the build command printed by this script
+
+TARGET_PHONE="${TARGET_PHONE:=zenfone8}"
+
+ROM_TYPE="${ROM_TYPE:=user}"
 
 # ---------------------------------------------------------------------
 # check for the parameter -h or --help
@@ -74,13 +111,19 @@ if [[ $0 = *print_security_patch ]] ; then
   if [ "$1"x = "-h"x -o  "$1"x = "--help"x ] ; then
     echo "${SCRIPT_NAME} ${SCRIPT_VERSION}"
     grep -E "^#h#" $0 | cut -f2- -d " "
+    echo "Environment variables supported by this script:"
+    echo
+    for CUR_VAR in $( grep -E "^[A-Z].*:=" $0 | cut -f1 -d "=" ); do
+      echo "${CUR_VAR} - current value is $( eval echo \\\"\$$CUR_VAR\\\" )"
+    done
+    echo
     exit 99
   fi
 fi
 
 
 # ---------------------------------------------------------------------
-# old build config file
+# old build config file 
 #
 VERSIONS_DEFAULTS_MK="./build/make/core/version_defaults.mk"
 
@@ -89,37 +132,64 @@ VERSIONS_DEFAULTS_MK="./build/make/core/version_defaults.mk"
 #
 BUILD_ID_FILE="./build/core/build_id.mk"
 
-
 BUILD_RELEASE_DIR="build/release"
 
 RELEASE_CONFIG_MAP_FILE="${BUILD_RELEASE_DIR}/release_config_map.mk"
 
 # ---------------------------------------------------------------------
-
+# variables for the values found in the repository
+#
 RELEASE_PLATFORM_SECURITY_PATCH=""
 BUILD_ID=""
+
+# variables using the values found in the repository
+#
 REPO_FORMAT=""
+BUILD_COMMAND=""
+
+# ---------------------------------------------------------------------
+# variables for the build command printed by this script
+
+PRINT_BUILD_COMMAND=${__FALSE}
+PRINT=""
+
+PRINT_GLOBAL_VARIABLES=${__FALSE}
+PRINTVARS=""
+
+GLOBAL_VARIABLES="TARGET_PHONE  ROM_TYPE BUILD_COMMAND "
+GLOBAL_VARIABLES_IN_THE_REPO="RELEASE_PLATFORM_SECURITY_PATCH BUILD_ID REPO_FORMAT "
+
+# undocumented environment variable 
+#
+  SEPARATOR_LINE="${SEPARATOR_LINE:=# -------------------------------------------------------------------------------------------------------------------------------- }"
 
 # ---------------------------------------------------------------------
 
 THISRC=0
 
-OUTPUT_ON_ONE_LINE=1
-
 # ---------------------------------------------------------------------
+# functions
+#
+
+function LogMsg {
+   echo "$*"
+}
 
 function LogInfo {
   if [ "${VERBOSE}"x != ""x ] ; then
-    echo "$*"
+    LogMsg "INFO: $*"
   fi
 }
 
+function LogWarning {
+  LogMsg "WARNING: $*" 
+}
+
 function LogError {
-  echo "ERROR: $*" >&2
+  LogMsg "ERROR: $*" >&2
 }
 
 # ---------------------------------------------------------------------
-
 # print the security patch level used in repository tree for the Android OS
 #
 function print_security_patchlevel_of_a_repository {
@@ -139,7 +209,7 @@ function print_security_patchlevel_of_a_repository {
     if [ -r "${VERSIONS_DEFAULTS_MK}" ]  ;then
       REPO_FORMAT="old"
 
-      LogInfo "Raeding the values from the source file \"${VERSIONS_DEFAULTS_MK}\" ..."
+      LogInfo "Reading the values from the source file \"${VERSIONS_DEFAULTS_MK}\" ..."
 
       RELEASE_PLATFORM_SECURITY_PATCH="$( grep "^[[:space:]]*PLATFORM_SECURITY_PATCH[[:space:]]*:=" "${VERSIONS_DEFAULTS_MK}" 2>/dev/null | awk '{ print $NF }'  )"
       BUILD_ID="$( grep "^[[:space:]]*DEFAULT_PLATFORM_VERSION[[:space:]]*:="  "${VERSIONS_DEFAULTS_MK}" | awk '{ print $NF }' )"
@@ -177,25 +247,25 @@ function print_security_patchlevel_of_a_repository {
       fi
     fi
     
-    if [ ${OUTPUT_ON_ONE_LINE} != 0 ] ; then
+    if [ ${OUTPUT_ON_ONE_LINE} != ${__TRUE} ] ; then
       if [ "${REPO_FORMAT}"x != ""x ] ; then
-        echo "The repository uses the ${REPO_FORMAT} definitions"
+        LogMsg "The repository uses the ${REPO_FORMAT} definitions"
       fi
       
       if [ "${RELEASE_PLATFORM_SECURITY_PATCH}"x != ""x ] ; then
-        echo "The current security patch is \"${RELEASE_PLATFORM_SECURITY_PATCH}\" "
+        LogMsg "The current security patch is \"${RELEASE_PLATFORM_SECURITY_PATCH}\" "
       else
-        echo "Can not detect the current security patch"
+        LogMsg "Can not detect the current security patch"
       fi
       
       
       if [ "${BUILD_ID}"x != ""x ] ; then
-        echo "The current build_id is \"${BUILD_ID}\" "
+        LogMsg "The current build_id is \"${BUILD_ID}\" "
       else
-        echo "Can not detect the current build id"
+        LogMsg "Can not detect the current build id"
       fi
     else
-      echo "Repository: ${PWD}, Patch Level: ${RELEASE_PLATFORM_SECURITY_PATCH}, Build ID: ${BUILD_ID}, Repository format: ${REPO_FORMAT} "
+      LogMsg "Repository: ${PWD}, Patch Level: ${RELEASE_PLATFORM_SECURITY_PATCH}, Build ID: ${BUILD_ID}, Repository format: ${REPO_FORMAT} "
     fi
   fi
 
@@ -232,7 +302,7 @@ function print_security_patchlevel_in_an_image_zip_file {
       LogError "The statement \"post-security-patch-level=<date>\" is missing in the file \"${METADATA_FILE}\" from the ZIP file \"${CUR_ZIP_FILE}\" "
       THISRC=203
     else
-      echo "ZIP File: ${CUR_ZIP_FILE}, Patch Level: ${POST_SECURITY_PATCH_LEVEL}"
+      LogMsg "ZIP File: ${CUR_ZIP_FILE}, Patch Level: ${POST_SECURITY_PATCH_LEVEL}"
       THISRC=0
     fi
   fi
@@ -246,25 +316,108 @@ function print_security_patchlevel_in_an_image_zip_file {
 
 LogInfo "${SCRIPT_NAME} ${SCRIPT_VERSION}"
 
-if [ $# -eq 0 ] ; then
-  echo "Retrieving the security patch level for the repository at \"${PWD}\" ..."
-  print_security_patchlevel_of_a_repository
+[ ${PRINT_BUILD_COMMAND} != ${__FALSE} ] && PRINT="0"
+
+[ ${PRINT_GLOBAL_VARIABLES} != ${__FALSE} ] && PRINTVARS="0"
+
+NO_OF_REPOS=0
+
+
+PARAMETER_FOUND=${__FALSE}
+for CUR_PARAMETER in $* ; do
+  [[ ${CUR_PARAMETER} != *=* ]] && PARAMETER_FOUND=${__TRUE} || (( NO_OF_REPOS =  NO_OF_REPOS + 1 ))
+done
+
+
+LIST_OF_PARAMETERS="$*"
+
+if [ ${PARAMETER_FOUND} = ${__FALSE} ] ; then
+  LogMsg "Retrieving the security patch level for the repository at \"${PWD}\" ..."
+  LIST_OF_PARAMETERS="${LIST_OF_PARAMETERS} ${PWD}"
+  OUTPUT_ON_ONE_LINE=${OUTPUT_ON_ONE_LINE:=${__FALSE}}
 else
-  OUTPUT_ON_ONE_LINE=0
+  OUTPUT_ON_ONE_LINE=${OUTPUT_ON_ONE_LINE:=${__TRUE}}
+fi
+
+
+if [ 0 = 0 ] ; then
   
-  for CUR_PARAMETER in $* ; do
+  for CUR_PARAMETER in ${LIST_OF_PARAMETERS} ; do
+
+    RELEASE_PLATFORM_SECURITY_PATCH=""
+    BUILD_ID=""
+    REPO_FORMAT=""
+    BUILD_COMMAND=""  
+
+    if [[ ${CUR_PARAMETER} = *=* ]] ; then
+      LogInfo "Executing now \"${CUR_PARAMETER}\" ..."
+      eval "${CUR_PARAMETER}" 
+      if [ $? -ne 0 ] ; then
+        LogError "Error executing \"${CUR_PARAMETER}\" "
+        exit 251
+      else
+        continue
+      fi
+    fi
   
     if [ -d "${CUR_PARAMETER}" ] ; then
-      LogInfo "Retrieving the security patch level for the repository at \"${CUR_PARAMETER}\" ..."
+      
+      if [ "${PRINT}"x != ""x -o "${PRINTVARS}"x != ""x ] ; then
+        [ ${NO_OF_REPOS} != 0 ] && LogMsg "${SEPARATOR_LINE}"
+        LogMsg "Retrieving the security patch level for the repository at \"${CUR_PARAMETER}\" ..."
+      fi
       
       cd "${CUR_PARAMETER}"
       if [ $? -ne 0 ] ; then
         LogError "Can not change the working directory to \"${CUR_PARAMETER}\" "
         THISRC=240
       else
+   
         print_security_patchlevel_of_a_repository
         TEMPRC=$?
         [ ${TEMPRC} -gt ${THISRC} ] && THISRC=${TEMPRC}
+        if [ ${TEMPRC} -le 1 ] ; then
+          if [ "${PRINT}"x != ""x  ] ; then
+
+            if [ ! -d vendor/omni/ ] ; then
+              LogWarning "This is not a repository for the OmniROM - the build command for this repo is not known by this script"
+            else
+              if [ "${REPO_FORMAT}"x = "new"x ] ; then
+                export BUILD_COMMAND="brunch ${TARGET_PHONE} ${BUILD_ID} ${ROM_TYPE}"
+              else
+                export BUILD_COMMAND="brunch omni_${TARGET_PHONE}_${ROM_TYPE}"
+              fi
+   
+              LogMsg "
+# The command to build the image in the directory \"${CUR_PARAMETER}\" is:
+
+${BUILD_COMMAND}
+"
+            fi        
+          fi
+          
+          if [ "${PRINTVARS}"x != ""x  ] ; then
+            LogMsg ""
+            LogMsg "The values for the global variables defined in this script or in the script parameter are:"
+            LogMsg ""
+  
+            for CUR_VAR in ${GLOBAL_VARIABLES} ; do
+              eval "CUR_VALUE=\"\$${CUR_VAR}\""
+              LogMsg "${CUR_VAR}=\"${CUR_VALUE}\""
+            done
+
+            LogMsg ""
+            LogMsg "The values for the global variables found in the repos in the directory \"${CUR_PARAMETER}\" are:"
+            LogMsg ""
+
+            for CUR_VAR in ${GLOBAL_VARIABLES_IN_THE_REPO} ; do
+              eval "CUR_VALUE=\"\$${CUR_VAR}\""
+              LogMsg "${CUR_VAR}=\"${CUR_VALUE}\""
+            done
+
+            LogMsg ""
+          fi
+        fi
       fi
     elif [ -f ${CUR_PARAMETER} ] ; then
       LogInfo "Retrieving the security patch level used in the zip fole \"${CUR_PARAMETER}\" ..."
@@ -279,6 +432,14 @@ else
 fi
 
 # ---------------------------------------------------------------------
+
+
+
+# ---------------------------------------------------------------------
+
+
+# ---------------------------------------------------------------------
+
 
 if [[ $0 = *print_security_patch ]] ; then
   exit ${THISRC}
